### ISSUE TITLE
[FEATURE REQUEST] convert to cbz, instead of pdf?

### ISSUE THREAD

**Issue by grillgamesh** [Scallywagon/NHentai-Favorites-Downloader#1]
I dislike reading pdfs for manga, there's a file format named .cbz (which is essentially a zip file)
not sure if the following code works properly, as I'm not super well versed in python, and had chatGPT help out a lot.
```

import zipfile
import os
from PIL import Image

def compress_to_cbz(img_paths, title):
    # Define the path to save the .cbz file
    cbz_file_path = f'C:/Users/Jamie/Downloads/{title}.cbz'
    
    try:
        # Create a zip file with .cbz extension
        with zipfile.ZipFile(cbz_file_path, 'w') as cbz:
            for img_path in img_paths:
                # Open the image to ensure it's valid
                with Image.open(img_path) as img:
                    # Ensure image is saved in a proper format (if necessary)
                    img_format = img.format.lower()  # Get the image format (e.g., jpg, png)
                    
                    # Add the image to the cbz file
                    img_filename = os.path.basename(img_path)  # Get the image filename
                    cbz.write(img_path, img_filename)  # Add the image to the cbz archive
        
        print(f'CBZ saved to {cbz_file_path}')
    except Exception as e:
        print(f"Error creating CBZ: {e}")
```

ALSO: 
maybe make it a prompt for where to save the files...? C:\Jamie\Downloads wouldnt be a good spot, if your username isnt Jamie :P

**Comment by grillgamesh** [comment]
i got it working, mostly.
opening a pull request.

**Comment by grillgamesh** [comment]
see https://github.com/grillgamesh/NHentai-Favorites-Archiver/blob/main/SAVE_EVERYTHING%20-%20Copy.py, it converts to a cbz.

**Comment by SillyViking** [comment]
Wow thank you so much for the idea! 
Yes I believe converting it to .cbz would probably be a better idea than pdfs. Do you know of any other file formats that users would like to read in?

**Comment by SillyViking** [comment]
Also regarding the file path, I wrote the script in a rush since I didnt want my assets lost lol

**Comment by grillgamesh** [comment]
> Also regarding the file path, I wrote the script in a rush since I didnt want my assets lost lol

lol, i get it.
I like cbz, but some people like .epub.
check my repo for the working code. I've only gotten CBZ done, and i'm letting it run in the background.
remember to ensure the security settings of your folders let "Everyone" be able to write and modify files to, I discovered that it was erroring 30 mins ago sildently due to that lol.

**Comment by SillyViking** [comment]
Added cbz support while leaving the pdf compressor inside (see newest commit). will have to look at the security settings though

**Comment by SillyViking** [comment]
@grillgamesh did you manage to archive everything successfully?

**Comment by grillgamesh** [comment]
> @grillgamesh did you manage to archive everything successfully?

sometimes crashes due to an element not being clickable.... which nuked like 10 doujins that I had to find, and reset the counter for, but otherwise yeah it's still going along strong. 245 left. will update when it hits 0.

BTW: Calibre can do an over-the-web e-reader, so you can set up your doujins in calibre, start the content server, and then read your books in your phone or tablet's web browser, no need for google books or whatever you use. I recently found that out this morning, so that was a nice suprise.

**Comment by grillgamesh** [comment]
It's all archived.
